### ISSUE TITLE
traceback from check_init_admin.py after upgrade to 6.0.9

### ISSUE THREAD

**Issue by resuser** [haiwen/seafile-server#37]
Starting from 4.2.2, I ran though the upgrade steps to get to 6.0.9 on my Ubuntu 14.04.5 sever.  I get the following when attempting to restart seafile-server:

`$ sudo service seafile-server restart

Traceback (most recent call last):
  File "/seafilebase/as3/seafile-server-6.0.9/check_init_admin.py", line 352, in <module>
    rpc = RPC()
  File "/seafilebase/as3/seafile-server-6.0.9/check_init_admin.py", line 289, in __init__
    ccnet.ClientPool(ccnet_dir, central_config_dir=central_config_dir))
TypeError: __init__() got an unexpected keyword argument 'central_config_dir'
`
Where did I go wrong and how do I fix this?
Thanks

**Comment by shoeper** [comment]
This is an issue tracker. Please use the [forum](https://forum.seafile.com/) for questions.

**Comment by resuser** [comment]
Hi shoeper,

What defines an "issue"?  I went through the upgrade process properly, and seahub broke.  I did post in the forums as you instructed, and several people have attempted to help, but so far no luck.
https://forum.seafile.com/t/traceback-from-check-init-admin-py-after-upgrade-to-6-0-9/2506/

This appears to me to be a bug.

**Comment by killing** [comment]
Closing this issue since it should be discussed on forum. Github is only a bug tracker.
